= Ansible Collection - eraga.matrix

Collection of modules to manage Matrix Homeserver instance. Only tested with Synapse but may (partially) work with
the other Matrix Homeserver implementations.

== Features

* Manage Users (synapse server only via https://github.com/matrix-org/synapse/blob/develop/docs/admin_api/user_admin_api.rst[synapse admin api]):
** [x] register,
** [x] update,
** [x] deactivate.
* Manage Rooms:
** [x] create;
** [x] update;
** [x] delete (via https://github.com/matrix-org/synapse/blob/develop/docs/admin_api/rooms.md#delete-room-api[synapse admin api]);
** [x] invite room members;
** [x] kick room members;
** [x] update room avatar.
** [ ] ability to reference room by the `id` instead of `alias`.
* Manage Communities:
** [ ] create;
** [ ] update;
** [ ] delete;
** [ ] kick/invite members.
** [ ] update avatar.
* Send messages to matrix rooms:
** [x] unencrypted messages:
*** [x] markdown text;
*** [ ] images;
*** [ ] file attachments;
** [ ] encrypted messages.


== Dependencies

All dependencies are gathered in role `eraga.matrix.module_dependencies`.

[source, yaml]
----
ifndef::env-github[]
include::roles/module_dependencies/tests/test.yml[]
endif::[]
ifdef::env-github[]
---
- hosts: localhost
  roles:
    - eraga.matrix.module_dependencies
endif::[]
----


== Examples

=== Send a message to Matrix room

[source, yaml]
----
---
- name: Send a message to the room
  connection: local
  hosts: localhost
  gather_facts: false
  vars:
    matrix_uri: "https://matrix.example.net"
    matrix_token: "redacted"
    matrix_user: "ansible"
  roles:
    - eraga.matrix.module_dependencies
  tasks:
    - name: Set some fact
      set_fact:
        variables: "__variables__"

    - name: Send text to room
      eraga.matrix.send:
        matrix_uri: "{{matrix_uri}}"
        matrix_user: "{{matrix_token}}"
        matrix_token: "{{matrix_user}}"
        matrix_domain: example.net
        room: ansible_example_room_1
        text: |
          ## Test message

          It *supports* mardown and jinja {{variables}} (of course)

----

=== Sync user accounts and rooms from external Identity Provider (e.g. JetBrains Hub)

[source, yaml]
----
---
- name: Sync users and project rooms from JetBrains Hub instance to Matrix Synapse
  connection: local
  hosts: localhost
  gather_facts: false
  vars:
    hub_uri: "https://hub.example.net/hub"
    hub_token: "redacted"

    matrix_uri: "https://matrix.example.net"
    matrix_token: "redacted"
    matrix_user: "ansible"

    all_users: []
  roles:
    - eraga.matrix.module_dependencies
  tasks:
    - name: Get Hub projects with fields and query
      eraga.jb_hub.projects:
        hub_uri: "{{hub_uri}}"
        hub_token: "{{hub_token}}"
        query: "not is: global"
        fields: "name,key,team(users(login,banned,avatar,name))"
      register: projects_result

    - name: Aggregate all unbanned users
      set_fact:
        all_users: "{{ project.team.users  | rejectattr('banned', 'true') | eraga.jb_hub.user2dict | union(all_users) }}"
      with_items: "{{projects_result.projects}}"
      loop_control:
        loop_var: project
        label: "{{ project.key }}"

    - name: Ensure user {{user.login}} exists in Matrix and has synced profile
      eraga.matrix.user:
        matrix_uri: "{{matrix_uri}}"
        matrix_user: "{{matrix_user}}"
        matrix_token: "{{matrix_token}}"
        matrix_domain: example.net
        login: "{{user.login}}"
        avatar: "{{user.avatar_url | default(omit) }}"
        displayname: "{{user.name | default(omit) }}"
      with_items: "{{all_users}}"
      loop_control:
        loop_var: user
        label: "{{ user.login }}"

    - name: Room for Hub Project exists and room members are synced
      eraga.matrix.room:
        matrix_uri: "{{matrix_uri}}"
        matrix_user: "{{matrix_user}}"
        matrix_token: "{{matrix_token}}"
        matrix_domain: example.net
        alias: "{{ project.key | lower }}_general"
        name: "{{ project.name }}"
        topic: This is room managed by ansible, yay!
        federate: no
        visibility: private
        preset: private_chat
        encrypt: yes
        room_members: "{{ project.team.users | rejectattr('banned', 'true') | map(attribute='login') | eraga.matrix.list2members(0) }}"
        power_level_override:
          events_default: 0
          state_default: 90
          ban: 90
          kick: 50
          redact: 50
          invite: 10
      with_items: "{{projects_result.projects}}"
      loop_control:
        loop_var: project
        label: "{{ project.key }}"
----
