---
- name: Ensure latest versions of dependencies installed
  package:
    name: "{{matrix_modules_package_dependencies}}"
    state: latest

- name: Ensure python dependencies present
  pip:
    name: "{{matrix_modules_pip_dependencies}}"
    state: present
